server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/founderlink_auth
    username: snehalsuman
    password: Snehal@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:snehals0203@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:uzte iyhv uryb mhdh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  exchange: founderlink.exchange

app:
  admin:
    password: ${ADMIN_PASSWORD:Admin@123}

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
