server:
  port: 8087

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/founderlink_notifications
    username: snehalsuman
    password: Snehal@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: founderlink.exchange
  queue:
    investment-created: investment.created.queue
    investment-approved: investment.approved.queue
    team-invite-sent: team.invite.sent.queue
    startup-created: startup.created.queue
    startup-rejected: startup.rejected.queue
    payment-success: payment.success.queue

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
